### ISSUE TITLE
Genre links from individual movie views points to tvshows, not movies

### ISSUE THREAD

**Issue by petterreinholdtsen** [xbmc/chorus2#398]
I am using Chrous2 version 18.x-2.4.6 with Kodi version 18.5.

When looking at a movie with genre information, I expect to be able to click on the genre name and get a list of other movies with the same genre.  Instead, I am sent to the list of TV shows with the genre in question, in my case normally an empty link.

It seem to me like likes like .../#tvshows?genre=Documentary should go to 
.../#movies?genre=Documentary instead.  Could the web pages be changed to do so?

**Comment by malard** [comment]
this looks like it has been fixed a long time ago

**Comment by petterreinholdtsen** [comment]
[Martin Ellis]
> this looks like it has been fixed a long time ago

Glad to hear.  Any idea when the fix will show up in nexus, where I
still experience it?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by malard** [comment]
its specifically working for me with the latest official 20.x release, so if its not working for you, please be more specific, which page, screenshots whatever to help me :)

**Comment by KarellenX** [comment]
I just checked this, and I am the same as the OP where clicking on the genre takes me to tv shows.

The help page in Chorus shows the version as 19.x-2.4.8 and Kodi version 21.0

But looking in the repo all I see is this... https://mirrors.kodi.tv/addons/omega/webinterface.chorus/ and that version number is lower than what I currently have.

**Comment by malard** [comment]
same question again, please can someone give me a picture with a big arrow pointing at where you are referring to please

**Comment by KarellenX** [comment]
Here...

![chorus](https://github.com/xbmc/chorus2/assets/44626605/aba24405-a2a7-4ce0-88e7-7325001da5f2)

![chorus2](https://github.com/xbmc/chorus2/assets/44626605/c8dcc5e9-c293-46c4-a60a-7d284e8c73f2)

**Comment by malard** [comment]
amazing thanks, i was scrolling down the page and clicking on the "More from Comedy" link :) i will get this fixed tomorrow
